let parrains = [
  "Abdel Nassif ABDOURAHAMANE ALILOU",
  "Bessel Vestel Patient AÏNA",
  "Idrissa Pathé Ngoné BALDE",
  "Clairemode Placida Sétchèmé ALLOKPENOUDJI",
  "Mouhammadou Ba",
  "Chaïkou Oughaïlou BALDE",
  "Fatou Kine BARRO",
  "Abdel Kader BARRY",
  "Alain Chris Exaucé BOUDOUA",
  "Khady CASSE",
  "Mouhamadou Gorgui CISSE",
  "Ahmada CISSE",
  "Eunice Audine Assiba CODO",
  "Fatoumata DIA",
  "Cheikh Omar DIABAKHATE",
  "Mouhammad DIALLO",
  "Kadiatou Aliou DIALLO",
  "Alpha Oumar DIALLO",
  "Adama DIASSE",
  "Yssouf DIATARA",
  "Julie DIATTA",
  "Diarra DIAW",
  "Sokhna Mbacké DIENG",
  "Birama DIENG",
  "Ndeye Coura DIONG",
  "Khadidiatou DIONG",
  "Saïd Fayez DIOP",
  "Fatou DIOP",
  "Arona DIOP",
  "Fatou Kine DIOP",
  "Mansour DIOP",
  "Adja Fatou DIOP",
  "Insa Saer DIOP",
  "Magatte DIOUF",
  "Awa Cheikh DIOUF",
  "El Hadji Malick DRAME",
  "Bignon David A.rOLAND FACOUNDE",
  "Ibrahima Ngary FALL",
  "Fatou FALL",
  "Mouhamadou Moustapha FALL",
  "Alioune Badara FALL",
  "Serigne Saliou FAYE",
  "Mouhamed Lamine FOFANA",
  "Amine O.R. Roland GBADAMASSI",
  "NDIAMBE GUEYE",
  "Maguette Gueye",
  "Ali KA",
  "EL-REYAD KALDANSE",
  "Dominique Niakar KAMA",
  "Souleymane KAMARA",
  "Silamakan KAMISSOKO",
  "Mamadou Aboubekrine KANE",
  "Roukiatou KEITA",
  "Bintou kOUYATE",
  "Alioune LO",
  "Cheikh LO",
  "Renel-Suzan LOULONGANOU",
  "Awa Doudou LOUM",
  "Cephas-Ben-Adi MAHOUNGOU",
  "NOH MAÏDE HANGATTA",
  "Abou Bakry Yaya MARENA",
  "Ousmane MBACKE",
  "Diariatou MBAYE",
  "Mame Diarra MONTEIRO",
  "Yaye Amy NDAO",
  "El Hadj Serigne Fallou NDAO",
  "Marie NDIAYE",
  "Aly NDIAYE",
  "Momar NDIONE",
  "Amadou Moctar NDJIM",
  "Mouahamedou Wedji NIANG",
  "Mamadou Mactar NIANG",
  "Akhmadou Mokhtar NIANG",
  "Mariam Issa NOKOUR",
  "Ghislain Wendy ONDIA TCHIPALA",
  "Marwan RABE DJIBRIL",
  "Mouhssine Adjassa RADJI",
  "Gnagna Ba SALL",
  "Amadou SALL",
  "Serigne Khadim Gaydel SAMB",
  "Silobil Cheikh Tidiane SAMBOU",
  "Jean Bruno SARR",
  "Bara SARR",
  "Aïcha Elisabeth SARR",
  "Fatou Mbagnick SARR",
  "Aïcha Dalloba SAVANE",
  "Angélique Julie SECK",
  "Aminata Ngoné SEMBENE",
  "Bonco SOW",
  "El Hadj OMAR SOW",
  "Aliou Alassane SOW",
  "Rokhéya SY",
  "Mohamed Foulayah SYLLA",
  "Mariama Victoire SYLLA",
  "Mame Diarra Bousso TALL",
  "Marième THIAM",
  "Bada Diaw THIOUB",
  "Mounira T.S. Alake TIDJANI",
  "Rokhaya Diagne TOURE",
  "Ndeye Fatou TOURE",
  "Aboubacar TRAORE",
  "Yatsine Fidelia WINGNANNOU",
  "Al Amine YOUSSOUF MUHAMMAD",
  "Lam Sakho Ngone",
  "Glory Ugochi AGU",
  "Dia Ramatoulaye",
  "José Da Costa  Erickson",
  "Khadidiatou BEYE",
];
let filleuls = [
  "Ely AHMED MESSOUD",
  "Mané AIDARA",
  "Amy Cheikh Dite Natta AMAR",
  "Ndeye Fatou ANNE",
  "Marie Gabrielle Acobty ASSINE",
  "Ikbal AZIMARI TOURE",
  "Moussa Yaghouba BA",
  "Talla Cissé BA",
  "Mouhamadou Mansour BA",
  "Djibril BA",
  "Aboubacry BA",
  "Mamadou BA",
  "Safiétou Mariama Abiodoun Titilokpé BADJI",
  "Ervy Divine BANSIMBA",
  "Dexter Tendre Fortune BONGO MABIKA",
  "Safiatou BOURAMA MOUMOUNI",
  "Seydina Mouhamadou CAMARA",
  "Ousmane CISSE",
  "Charles Nelson Odinga CORREA",
  "Mouhamed Lawal DAN AZOUMI",
  "Seydou DANSOGO",
  "Aminata DIAGNE",
  "Adja Ndeye Mariéme DIAGNE",
  "Mouhamed DIAGNE",
  "Moussa Diouf DIALLO",
  "Abdoulaye DIALLO",
  "Ndeye Seynabou DIAW",
  "Amadou Maadou DIENG",
  "Ndeye Amy Gallo DIOP",
  "El Hadj Moctar Gamby DIOP",
  "Aissatou Sophiane DIOP",
  "Mamadou DIOP",
  "Ibrahima DIOP",
  "Aminata DIOP",
  "Abdoukarim DIOP",
  "Mouhamadou Lamine DIOUF",
  "Khodia DIOUF",
  "Tchopou DJAPO -ALI",
  "Maty DJIGO",
  "Saliou DRAME",
  "Aissatou FALL",
  "Kalidou FALL",
  "Awa FAYE",
  "Ndéye Penda FISSURU",
  "Ahmadou Abdoulahi GAYE",
  "Mouhamed Al Amine Gueye",
  "Fatou Gueye",
  "Aminata GUISSE",
  "Habiboulahi ISSA SEYDOU",
  "Salim ABDOU HAMANI",
  "Abdourahmane IDA ABDOULAYE",
  "Salamatou ISMAEL BADA",
  "Massamba Roldy JEANCY",
  "Kodjo Felix KALAWA",
  "Maguette Ndiaye KANE",
  "Laeticia Tarmadji KEMGUERBAYE",
  "Pape Becaye LAMOTTE",
  "Bassirou LOUM",
  "Abdoul Wahab LY",
  "Kassy MAIGA",
  "Maria Lise MAKITA MBOU",
  "Coumba MBAYE",
  "Adja Ngoné MBAYE",
  "Awa Cissé MBOUP",
  "Ngakoutou Junior MOSSEDE",
  "Prince -Victorien NDAMBA",
  "Babacar NDAW",
  "Khoudia NDIAYE",
  "Mouhamed NDIAYE",
  "Nafissatou NDIAYE",
  "Ahmadou NDIAYE",
  "Ndeye Mour NDIAYE",
  "Seydina Laye NDIAYE",
  "Ndeye Aissatou NDOYE",
  "Abdoul Malick Maodo NIANG",
  "Sokhna Ndakhté Khar Fall NIANG",
  "Pape Alioune NIASSE",
  "Olafemi Erick Valere NOUNAWON",
  "Laurentino Mangue NVO ABENG",
  "Kofi Inalé OBYMPE",
  "Georges Lexance OKYERI",
  "Manira OUSMANE HAMISSOU",
  "Mansour POUYE",
  "Abdoulaye SALL",
  "Ndeye Nafissatou SALL",
  "Aboubakar SALY",
  "Fatoumata Moubarak SAMBA",
  "Khady SECK",
  "El Hadji Malick SECK",
  "Khalil Mayacine SEYE",
  "Omar SOW",
  "Moussa Amadou SOW",
  "Aby SY",
  "Mamadou Bocar SY",
  "Manoumbé SYLLA",
  "Ndeye Fatou SYLLA",
  "Olivier TCHIKAYA DAMPOUYA",
  "Abakar Alhadj TERAP",
  "Mouhamadou Saliou THIAM",
  "Mamadou Moustapha THIAM",
  "Mamadou Lamine THIORE",
  "Mouhamadou TIRERA",
  "Fatou Kiné TOP",
  "El Hadj Alioune TRAORE",
  "Racky WANE",
  "Mamadou Sada WANE",
  "Khadidiatou WELE",
  "Mouhamed NDIAYE",
  "Moussa LAM",
  "Maréme NDIAYE",
  "Junior MOSSEDE NGAKOUTOU",
  "Urbain Arimo Hans GNANSOUNOU",
  "Abibatou DIAGNE",
  "Oumar SOW",
  "Cheikh Ahmadou Bamba DIA",
  "Maimouna SARR",
  "Aida SYLLA",
  "Ndeye Obour NDIAYE",
];
let isParrainSet = false;
let current;
const button = document.querySelector("button");

function getRandomIndex(arrayLength) {
  return Math.floor(Math.random() * arrayLength);
}

function pickRandomPerson(currentClass) {
  const index = getRandomIndex(currentClass.length);
  return currentClass[index];
}

function displayParrainOrFilleul(location, currentClass) {
  current = pickRandomPerson(currentClass);
  document.getElementById(location).innerHTML = current;
}

function removePerson(currentClass, current) {
  currentClass.splice(currentClass.indexOf(current), 1);
  isParrainSet = !isParrainSet;
}

function matchUp() {
  let paragraph, currentArray;

  if (isParrainSet) {
    paragraph = "filleul";
    currentArray = filleuls;
  } else {
    paragraph = "parrain";
    currentArray = parrains;
  }
  document.getElementById(paragraph).style.fontSize = "150%";

  let repetition = 0;
  button.disabled = true;
  let animation = setInterval(function () {
    displayParrainOrFilleul(paragraph, currentArray);
    repetition++;
    if (repetition == 20) {
      button.disabled = false;
      document.getElementById(paragraph).style.fontSize = "300%";
      removePerson(currentArray, current);
      clearInterval(animation);
    }
  }, 100);
}
